services:
  webapp:
    restart: unless-stopped
    build: app
    networks:
      - app_network
  studio:
    restart: unless-stopped
    build: studio
    networks:
      - app_network
    env_file:
      - ./studio.env

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - webapp
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - app_network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
networks:
  app_network:
